### ISSUE TITLE
Improve Markdown Support

### ISSUE THREAD

**Issue by QuinnDamerell** [QuinnDamerell/Baconit#2]
* Support more markdown elements
 * Headers
 * Lists
 * Grids
 * Etc.
* Support links in runs (example support /r/Baconit in a bold text run)

**Comment by mvaneerde** [comment]
Need lots of test cases for this one :-)

**Comment by paulbartrum** [comment]
I've started working on this here: https://github.com/paulbartrum/Baconit/tree/improve-markdown-support

**Comment by QuinnDamerell** [comment]
Awesome! I actually just started on it last night also, I made a whole new project to write the parser in so eventually it can live on it's own and anyone can use it! I see you just started in your branch, I would suggest taking a look a the new stuff. The new stuff should be a lot easier to unit test. :)

https://github.com/QuinnDamerell/Baconit/tree/quinnd/markdown

**Comment by paulbartrum** [comment]
I went ahead and moved 76 unit tests into the new repo, and submitted it as a pull request.

There are lots of things that don't currently work:
* Currently line breaks in the input text are being translated to a new paragraph.  Correct behavior is that two (or more) spaces at the end of a line results in a line break, an empty line results in a new paragraph.  A line break on it's own should result in a space.
* Single and double underscores should be treated just like the star character.
* Bold and italic spans are not valid if they begin with a whitespace character.
* Bold and italic spans are not valid if the end with a whitespace character.
* Lists, tables and code blocks must begin on a new paragraph otherwise they are ignored.
* With numbered lists, the number should be ignored and replaced with sequential integers (1, 2, 3, etc).
* With numbered lists, a space is required after the dot (i.e. "1. The" not "1.The").  If there is no space the list should be ignored.
* For headers that start with hash characters, any trailing hash characters should be removed (e.g. "### header ###" should be rendered as "header").
* Headers can also be specified by putting a line consisting solely of dashes or equal signs directly below the heading text.
* Unsupported features: escape sequences, strike-through, superscript, tables.

**Comment by QuinnDamerell** [comment]
Awesome thanks! I realized after making this new project that we may be better off to use something like https://github.com/brandonc/moonshine. For now I am going to stick with the new parser, but it would be great if someone could look into what it would take to move to something like moonshine.

**Comment by nayanshah** [comment]
MoonShine hasn't been updated in a while. https://github.com/Knagis/CommonMark.NET is more recent and similar perf as MoonShine.

**Comment by QuinnDamerell** [comment]
Thanks! I will look into that when I start working on Markdown again. (or whoever else wants to pick this up)

After my first glance it might be tricky to make it convert to a rich textblock instead of html, but it might be possible.

**Comment by QuinnDamerell** [comment]
paulbartrum  did some awesome work in the markdown and I think we can call this one done.
